name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # This grants write permissions to the contents scope

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_TAG: "latest_release"

jobs:

  build_and_release:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: dotnet build --configuration Release HellDivers2OneKeyStratagem.sln

    - name: Zip
      run: Compress-Archive -Path ./bin/* -DestinationPath HellDivers2OneKeyStratagem.zip

    - name: Delete release and tag
      run: gh release delete ${{ env.RELEASE_TAG }} --cleanup-tag -y
      continue-on-error: true

    - name: Create a new tag and release
      run: gh release create ${{ env.RELEASE_TAG }} --generate-notes

    - name: Upload zip
      run: gh release upload ${{ env.RELEASE_TAG }} HellDivers2OneKeyStratagem.zip --clobber 
